[package]
name = "blocky_derive"
version = "0.1.0"
edition = "2021"

[lib]
name = "blocky_derive"
proc-macro = true

[dependencies]
quote = "1.0.33"
syn = { version = "2.0.29", features = ["full", "extra-traits"] }
